name: Test Push

on:
  push:
    branches: [ TESTNUGET]
  pull_request:
    branches: [TESTNUGET ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
          - uses: actions/checkout@v2
          - name: Setup .NET Core 3.1
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '3.1.101'
          - name: Setup .NET 5.0
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '5.0.100-preview.6.20318.15'
          - name: DOTNET HACK
    #  https://github.com/actions/setup-dotnet/issues/25
            shell: pwsh
            run: |
                $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
                $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
                $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };
                foreach ($dir in $directories) {
                  $from = $dir.FullName;
                  $to = "$root/$version";
                  Write-Host Copying from $from to $to;
                  Copy-Item "$from\*" $to -Recurse -Force;
                }
          
          - name: Install dependencies
            run: dotnet restore
  package:
    runs-on:  ubuntu-latest 
    needs: [build]
    if: github.ref == 'refs/heads/TESTNUGET'
    steps:
      - uses: actions/checkout@v2
      - name: Build_Package
        run : |
              dotnet pack Ryu.Net\\Ryu.NET.csproj -c Release --output=package_output
        id  : Build_Package
      #- name: Tag commit
      #  uses: tvdias/github-tagger@v0.0.1
      #  with:
      #    repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #    tag: "${{ steps.Build_Package.outputs.version }}"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package_output/*.nupkg"
          prerelease: ${{ github.ref ==  'refs/heads/prerelease'}}
          draft: false
          tag: "TEST_TAG"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Github Package
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path:  "package_output/*.nupkg"
          repo-owner:  'Narinder Claire'
          gh-user:  'Ninds'
          token:  ${{ secrets.GITHUB_TOKEN }}
    
